//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_TempHumidService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db1Entities1 : DbContext
    {
        public db1Entities1()
            : base("name=db1Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<HumidityMeasurement> HumidityMeasurements { get; set; }
        public DbSet<Location> Locations { get; set; }
        public DbSet<RMUnit> RMUnits { get; set; }
        public DbSet<TemperatureMeasurement> TemperatureMeasurements { get; set; }
    }
}
