//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_TempHumidService
{
    using System;
    using System.Collections.Generic;
    
    public partial class RMUnit
    {
        public RMUnit()
        {
            this.HumidityMeasurements = new HashSet<HumidityMeasurement>();
            this.TemperatureMeasurements = new HashSet<TemperatureMeasurement>();
        }
    
        public string Name { get; set; }
        public string LocationName { get; set; }
        public int Id { get; set; }
    
        public virtual ICollection<HumidityMeasurement> HumidityMeasurements { get; set; }
        public virtual Location Location { get; set; }
        public virtual ICollection<TemperatureMeasurement> TemperatureMeasurements { get; set; }
    }
}
